Test regex when adding a new phrase.
destinygg/chat-bot pull request #140
Opened 2023-12-23 06:22 UTC by Mitchdev

Also fixed a couple errors in the file return Command instead of CommandOutput.
and returning a non promise when the command requires a promise.

2023-12-24 11:25 UTC, 11k requested changes
How did `package-lock.json` change? Were you unable to install dependencies with `npm ci`?

2023-12-24 11:25 UTC, 11k commented on lib/commands/implementations/banphrase.js
> +        return new Promise((resolve) =>
Would you mind using `Promise.resolve(value)`? It's a little more concise than `new Promise((resolve) => resolve(value)`.

2024-01-14 01:00 UTC, Mitchdev commented
> How did `package-lock.json` change? Were you unable to install dependencies with `npm ci`?

Yeah had a problem with node-gpy not being able to install.

2024-01-22 07:10 UTC, 11k approved these changes

2024-01-22 07:10 UTC, merged